### ISSUE TITLE
Fed cleanup logic is not thread safe

### ISSUE THREAD

**Issue by fengsp** [ray-project/rayfed#130]
We are using multiple threads on the fed cleanup module, which has thread safety issues, for example:

1.  Main thread: global _check_send_thread is not None
2. _check_send_thread: clear global _check_send_thread variable to None
3. Main thread: calling _check_send_thread.join(), this would error because None object does not have join method

We should check all threading usage in ray fed and fix this.

**Comment by jovany-wang** [comment]
@zhouaihui @NKcqx CC as well.
