### ISSUE TITLE
cannot install ray fed from pip

### ISSUE THREAD

**Issue by tardism** [ray-project/rayfed#138]
(ray22) name:~$ pip install -U rayfed
ERROR: Could not find a version that satisfies the requirement rayfed (from versions: none)
ERROR: No matching distribution found for rayfed

Current conda environment has ray 2.20 installed.

**Comment by jovany-wang** [comment]
Hi, try `pip install rayfed-nightly` out!

**Comment by tardism** [comment]
Thank you!
