### ISSUE TITLE
Provide a forced shutdown option.

### ISSUE THREAD

**Issue by zhouaihui** [ray-project/rayfed#206]
## What happened
Demo code.
```python
@fed.remote
def error_fun():
    raise Exception('By design')

@fed.remote
def random():
    return [1, 2] 

@fed.remote
def foo(a):
    print(a)

try:
    # Alice ran into an error and broadcast error to bob. And exit then.
    a = error_fun.party('alice').remote()
    b = foo.party('bob').remote(a)
    
    # Alice did not execute the following codes.
    data = random.party('alice').remote()
    c = foo.party('bob').remote(data)
   # Bob was going to send c to alice but alice won't send `data` to bob since alice exited already. 
    foo.party('alice').remote(c)
    
   # Bob got the error.
    fed.get(b)

finally:
    # Bob was blocked here because data sending was hanging.
    fed.shutdown()
```

## A possible solution
Give an forced option to `fed.shutdown(forced=False)`, if `forced==True`, shutdown anyway ignoring the data sending.

**Comment by jovany-wang** [comment]
`fed.shutdown(forced=False)`
or 
`fed.force_shutdown()`
?

**Comment by zhouaihui** [comment]
We can hide the forced behavior.
Once bob received error from alice, the job became meaningless already(`exit_on_sending_failure==True`).
So bob can mark the job as failure when received an error from alice, and then do not wait for data sending when shutdown.

**Comment by zhouaihui** [comment]
`Receiving an error from peer` and `Error on self data sending` are same case actually. We should not wait data sending if error occurred no matter from alice itself or froom bob.

**Comment by jovany-wang** [comment]
> Receiving an error from peer and Error on self data sending are same case actually. We should not wait data sending if error occurred no matter from alice itself or from bob, since a job became meaningless already.

+ 1
