### ISSUE TITLE
Why rayfed still use secretflow-ray instead of ray as requirement

### ISSUE THREAD

**Issue by HurleyWu** [ray-project/rayfed#26]
https://github.com/secretflow/rayfed/blob/ba827c5345ae52cd38f96e15e4d0aced9de520bb/requirements.txt#L4

**Comment by zhouaihui** [comment]
hi, @HurleyWu, the same version of open source ray can be also competent. There is no functional difference between secretflow-ray and ray, except some trivial security enhancement.

**Comment by HurleyWu** [comment]
@zhouaihui Thanks for your reply! Will the certain security enhancement be merged into open source ray?

**Comment by jovany-wang** [comment]
We provide the identical security level on cross parties interactions in both secretflow-ray and ray.

The only difference between them is that we limit a little functionalities in secretflow-ray.

**Comment by HurleyWu** [comment]
@jovany-wang Will the little difference between ray and secretflow-ray be moved into **rayfed** or **open source ray**, since the secretflow-ray is closed source? Rayfed is an open source framework, but its dependency is a closed source, which I think is a bit inappropriate.

**Comment by ian-huu** [comment]
@HurleyWu We are looking for a proper way to open source secretflow-ray. At present, if you have some concerns about 'closed source', you can safely uninstall secretflow-ray and install the corresponding version of open source ray.

**Comment by jovany-wang** [comment]
@HurleyWu I see your concerns.

1. As @ian-huu said, we're finding a best practice to open source `secretflow-ray`.
2. The code of secretflow-ray could be found at Github https://github.com/alipay/ray/tree/dev/secretflow-ray-2.2.0 . There is only 1 commit on the top of community Ray.
3. Both `secretflow-ray` and `ray` are safe to use under the hook of `RayFed`.

**Comment by HurleyWu** [comment]
@jovany-wang @usbuild Thanks for your timely reply！ Since the code of secretflow-ray could be found at open source. I no longer have any doubts.

**Comment by jovany-wang** [comment]
More details about the dependencies could be found at https://github.com/ray-project/rayfed/issues/38

**Comment by jovany-wang** [comment]
This issue could be closed once rayfed 0.1.0 released.
