### ISSUE TITLE
Are there more details about the `simple and controllable protocols` for cross-solis Ray？

### ISSUE THREAD

**Issue by lidh15** [ray-project/rayfed#28]
从开源的代码里看rayfed在初始化时在ray的内部kv缓存中确定可以被反序列化的白名单类，然后就是普通的grpc+tls传输，不知道我的理解是否贴切？
想进一步了解的一是ray内部缓存这个中间件是experimental，这和rayfed想表达的生产级别安全性是否有一点点不搭？
二是目前代码块发布的版本展示了这个白名单类可以配置一些numpy ndarry之类的数据结构，但是隐语在做MPC、PSI这些操作时传输的数据结构是这样简单的吗，据群里专家介绍应该是通过pybind11包装了yet another crypto library里的数据结构吧，那么白名单该怎么写，或者说整个基于rayfed的MPC和PSI该如何实现，是否可以提供一些demo呢？
三是grpc+tls这里tls如果要使用SM2那么应该如何配置呢？据我了解似乎基于openssl是没法支持SM2的，在python grpc中实现这个有一定难度。

**Comment by jovany-wang** [comment]
Hi, could you translate the description in English? because this is maintained by a global organization.

**Comment by lidh15** [comment]
> Hi, could you translate the description in English? because this is maintained by a global organization.

Firstly, internal_kv of ray is experimental, is that really reliable?
Secondly, when I configure the fed grpc server with tls, how to use SM2 encryption instead of RSA?

**Comment by jovany-wang** [comment]
@lidh15 Thanks for the questions.
1. For the internal_kv, I don't know what the `reliable` you mean here. Although `internal_kv` is an experimental API, but it just write the configs to the backend storage of GCS, which works as the metadata storage of Ray. As a result that the `reliable` level here is the same as Ray's .

2. For the 2nd issue, maybe  @ian-huu and @zhouaihui will give a better answer.

**Comment by zhouaihui** [comment]
@lidh15 
About Q2, rayfed uses grpc as cross-silo communication rpc. Grpc supports tls, which uses RSA. AFAIK, grpc does not support SM2. By now, openssl 3.x supports chinese cryptography algorithm but not boringssl, which is used by grpc.

**Comment by jovany-wang** [comment]
Hi @lidh15 , do you have more questions?

**Comment by jovany-wang** [comment]
We should add these details into our documentation. Thanks for your suggestion.

**Comment by lidh15** [comment]
There are no more questions, just a little bit disappointed. On the one hand, marketing officers are advertising how bloody nice secretflow supporting Chinese cryptography algorithm, on the other hand, technique officers said it's all based on google's rpc and of course google has no interest on Chinese cryptograph algorithm.

**Comment by jovany-wang** [comment]
Let me keep it open.

**Comment by jovany-wang** [comment]
As discussed, different crypto module should be out of rayfed. For example, if we should enable SM2, they should be in the front of the parties, and proxy all requests, without implement it inside rayfed.
