### ISSUE TITLE
Change ray dependency version & release name

### ISSUE THREAD

**Issue by NKcqx** [ray-project/rayfed#38]
1. The current used ray dependency called "secretflow-ray", is it possible to just use "ray" ?
2. Our released package name is "secretflow-rayfed" rather than "rayfed", rename to "rayfed" can be easier to understand

**Comment by jovany-wang** [comment]
The package name could be changed firstly.
For the `ray` dependency, let us have a better decision before we cut it.

**Comment by jovany-wang** [comment]
The package name could be changed firstly.
For the `ray` dependency, let us have a better decision before we cut it.

**Comment by jovany-wang** [comment]
@ray-project/rayfed-dev CC

**Comment by NKcqx** [comment]
We suggest to continue to use `ant-ray` as other names related to "secure" may narrow down the semantics of "ray".
Other proposals are also welcomed.

**Comment by jovany-wang** [comment]
So the final names and dependency rules are:
1. `ant-ray` is the `ray` with functionalities enhanced. (Currently we only open source the enhanced functionalities for security issues, and the other major functionalities will be opened source in the future.
2. RayFed depends on `ant-ray`, and community `ray` can be optionally installed instead as the dependency as well.
3. Rename the package name of  this repo to `rayfed`.
