### ISSUE TITLE
Bug: the `cross_silo_messages_max_size_in_bytes` passed in fed.init is not reflected

### ISSUE THREAD

**Issue by Krout0n** [ray-project/rayfed#46]
Related: #31, #32, #36, #42 
I found a behavior where the global variable set by `set_max_message_length` is reset when the module is reloaded near the timing when the constructors of `SendProxyActor` and `RecverProxyActor` are called. I noticed this while working on https://github.com/ray-project/rayfed/pull/42#discussion_r1103938357, but thought it would be better to submit a separated Issue, so I did.

**Comment by jovany-wang** [comment]
Hi could you show the reproduced script?
Also CC @ray-project/rayfed-dev

**Comment by Krout0n** [comment]
Hi @jovany-wang! You can confirm it by 
- Checkout into my commit (https://github.com/ray-project/rayfed/pull/42/commits/1108a1e5664959797ced8365bf266d5853975964). The commit includes some planted `logger.info`.  
- Run `$ python3 -m pytest -v -s tests/tests_set_grpc_max_size_in_bytes.py`.  
- The console shows that the max bytes is `524288000` sometimes

**Comment by jovany-wang** [comment]
I'll take a look at this by the end of this week.

**Comment by jovany-wang** [comment]
I did't see this test `tests/tests_set_grpc_max_size_in_bytes.py`.

Could you give me a reproduced script? so that I might understand your issue.

**Comment by jovany-wang** [comment]
@zhouaihui @NKcqx Do you have any idea about this issue?

**Comment by jovany-wang** [comment]
@Krout0n 
Maybe you changed the test file name to `tests/test_cross_silo_messages_max_size_in_bytes.py`.

The reason for printing `524288000` is that you only set the max size for driver but we also have other processes like actors you hadn't set. The fix should be simple, not only it should be set for driver, but also it should be set for proxy actors.

**Comment by Krout0n** [comment]
@jovany-wang 
> Maybe you changed the test file name to `tests/test_cross_silo_messages_max_size_in_bytes.py.`

I'm sorry. Yes, I forgot that I renamed. 

So would you like a change to have `start_recv_proxy` and `start_send_proxy` receive the maximum number of bytes so that `RecevrProxyActor` and `SendProxyActor` can check the maximum number of bytes?

**Comment by jovany-wang** [comment]
Hi, I did fix your bug, you could apply the following patch. 
[fix-set-max-grpc-size.patch](https://github.com/ray-project/rayfed/files/10779178/fix-set-max-grpc-size.patch)

**Comment by jovany-wang** [comment]
Yes. You could pass the argument to the `SendProxyActor` and `RecvProxyActor`, and then add a method named `get_max_grpc_size` method for both the 2 actors,  and in your test, you could invoke the method as a remote function, like:
```python

def _get_max_grpc_size_from_send_proxy():
    o = send_proxy_actor.get_max_grpc_size.remote()
    return ray.get(o)
```

**Comment by jovany-wang** [comment]
Hi @Krout0n could i provide any help?

**Comment by Krout0n** [comment]
Hi @jovany-wang ! I'm busy with my day job, sorry. I'll get back to it over the weekend, so if you're in a hurry, you can have it patched instead of me. Thank you for your research🙏

**Comment by jovany-wang** [comment]
Thanks for the active contribution @Krout0n , so I'd like to help you finish it if you are busy. 

Could you add me into your repo (https://github.com/Krout0n/rayfed/tree/add-unittest-for-set_max_message_length)   so that I can help write the fix to your branch.

**Comment by jovany-wang** [comment]
Hi @Krout0n Due to this is a P0 issue that blocks our 0.1.0 release. I'm working on it.

**Comment by Krout0n** [comment]
Hi @jovany-wang very nice work! I learn from your patches. Thanks for your help!
