### ISSUE TITLE
[bug] cross_silo_grpc_retry_policy doesn't work.

### ISSUE THREAD

**Issue by zhaocaibei123** [ray-project/rayfed#67]
It seems that the argument `maxAttempts: 360` is not able to be set correctly. Please see the following error, it shows that the value is 5 instead of 360(I set it to 360).
![644fb478915f14696b86ef4409cb61f8](https://user-images.githubusercontent.com/48509226/220583199-d632d927-68b7-4b05-9a57-1638f389092c.png)

reproduced script:
![image](https://user-images.githubusercontent.com/48509226/220583942-07e56627-4d21-41c1-ae24-7394f1c3b720.png)

**Comment by jovany-wang** [comment]
@zhouaihui CC
Also we should change the the context in English due to this is a global community ~

**Comment by jovany-wang** [comment]
@zhaocaibei123 Could you give the reproduced script?
